export const EVENTS = [
  {
    id: 0,
    name: 'Turd Curling',
    emoji: '💩',
    attrs: ['ag', 'st'],
    attrNames: ['Agility', 'Strength'],
    type: 'target',
    description: 'Throw 3 cubes each. Score based on where they land. Push opponents off!',
    spaces: null,
  },
  {
    id: 1,
    name: 'Heavy Thing Throw',
    emoji: '🏋️',
    attrs: ['ag', 'st'],
    attrNames: ['Agility', 'Strength'],
    type: 'distance',
    description: 'Press your luck on the spiral, then throw for distance. Best of 3 counts.',
    spaces: null,
  },
  {
    id: 2,
    name: 'Who Even Likes to Run?',
    emoji: '🏃',
    attrs: ['sp', 'st'],
    attrNames: ['Speed', 'Strength'],
    type: 'race',
    description: '2-lap race over 16 spaces. Watch out for mud and hills!',
    spaces: 16,
    laps: 2,
  },
  {
    id: 3,
    name: 'Hurting Hurdles',
    emoji: '🏁',
    attrs: ['sp', 'ag'],
    attrNames: ['Speed', 'Agility'],
    type: 'race',
    description: '2-lap race over 18 spaces. Clear hurdles or lose your next turn!',
    spaces: 18,
    laps: 2,
  },
  {
    id: 4,
    name: 'Zoomie Dash',
    emoji: '💨',
    attrs: ['st', 'sp'],
    attrNames: ['Strength', 'Speed'],
    type: 'sprint',
    description: 'Roll Strength to load dice, get 5 matching for ZOOMIE! Sprint 13 spaces.',
    spaces: 13,
  },
  {
    id: 5,
    name: 'Big Boing',
    emoji: '🦘',
    attrs: ['sp', 'ag'],
    attrNames: ['Speed', 'Agility'],
    type: 'jump',
    description: 'Run up, stop before the line, jump! Unused speed dice = bonus agility.',
    spaces: null,
  },
]
